helm:
  parameters:
  - name: image.repository
    value: us-central1-docker.pkg.dev/gitops-lab-502912/gitops-demo/gitops-demo
    forcestring: true
  - name: image.tag
    value: 9df90a00f473ce67d58083472fec9e3c65a22c60
    forcestring: true
