helm:
  parameters:
  - name: image.repository
    value: us-central1-docker.pkg.dev/gitops-lab-502912/gitops-demo/gitops-demo
    forcestring: true
  - name: image.tag
    value: 136638e188766094d197028e170e54707c63e09e
    forcestring: true
